version: 2

models:
  - name: slv_estados
    description: >
      Estados brasileiros limpos e enriquecidos com classificacao IDH,
      quartil de PIB e ranking intra-regional. Serie 2019-2023.
    columns:
      - name: sigla_uf
        data_tests: [not_null]
      - name: ano
        data_tests: [not_null]
      - name: populacao
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 100000
              max_value: 50000000
      - name: pib_per_capita
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 5000
              max_value: 200000
      - name: idh
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
      - name: nivel_idh
        data_tests:
          - accepted_values:
              values: ["Muito Alto", "Alto", "Medio", "Baixo"]
      - name: quartil_pib
        data_tests:
          - accepted_values:
              values: [1, 2, 3, 4]

  - name: slv_municipios
    description: >
      Municipios com porte demografico, densidade e indicadores do estado pai.
    columns:
      - name: nome_municipio
        data_tests: [not_null]
      - name: sigla_uf
        data_tests: [not_null]
      - name: populacao
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1000
      - name: porte_municipio
        data_tests:
          - accepted_values:
              values: ["Metropole", "Grande", "Medio", "Pequeno", "Micro"]

  - name: slv_internacoes
    description: >
      Internacoes hospitalares limpas, enriquecidas com dados socioeconomicos da UF.
    columns:
      - name: id_aih
        data_tests: [not_null, unique]
      - name: sigla_uf
        data_tests: [not_null]
      - name: cid_principal
        data_tests: [not_null]
      - name: dias_internacao
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 365
      - name: valor_aih
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
      - name: obito
        data_tests:
          - not_null
          - accepted_values:
              values: [0, 1]
      - name: custo_por_dia
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1